### ISSUE TITLE
Support pull a specific commit/tag from Git (or later other VCS)

### ISSUE THREAD

**Issue by mssun** [mesalock-linux/mkpkg#5]
Since many MesaLock Rust packages are pinned in a specific commit or tag to keep updated, it's better to set commit hash or tag in source URL. We can borrow Arch Linux's format: `project_name::git+http://project_url#branch=project_branch`

  - https://wiki.archlinux.org/index.php/VCS_package_guidelines#VCS_sources
  - https://jlk.fjfi.cvut.cz/arch/manpages/man/PKGBUILD.5#USING_VCS_SOURCES

**Comment by mssun** [comment]
Ok, and the `project_name::` is not necessary for now.

**Comment by Arcterus** [comment]
Alright it should work now, so I'm going to close this.
